INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (6, 1, 'using column index', 'using column index');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (8, 1, 'THISISALLWORKING', 'THISISWORKINGVERYWELL');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (9, 1, 'TESTTESTTEST', 'TESTTESTTEST');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (10, 1, 'testing id printout', 'id printout');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (11, 1, 'testing the ability to limit duplicate data', 'test and test again');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (12, 1, 'dfsaf', 'dfsaf');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (13, 1, 'dfsaf', 'fsadf');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (14, 1, 'this is an ad test', 'this is an ad test');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (16, 1, 'this worked', 'this is working');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (17, 1, 'fdsjalf', 'fdsafkl;');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (18, 1, 'fdsafsd', 'fdsafasd');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (19, 1, 'cdasfasda', 'fadsfesafaew');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (20, 1, 'fsadf', 'ferwaf');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (22, 9, 'this is a new ad by the test user', 'Creating a new ad');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (23, 10, 'This ad is by testUser', 'testUser ad');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (26, 11, 'test ad', 'test ad');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (29, 20, 'test ad', '<script>alert("test")</script>');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (30, 1, 'hello', 'hiryan');
INSERT INTO adlister_db.ads (id, user_id, title, description) VALUES (31, 1, 'another test', 'another description');